version: '2'
services:    
  boot:
    image: busybox
    depends_on: 
      - app

  app:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-web
    volumes:
      - .:/opt/app
    working_dir: /opt/app/
    command: bash -c "npm install && nodemon"
    links:
      - redis
      - mysql
    ports:
      - "3000:3000"

  redis:
    image: redis
    ports:
      - "6379"

  mysql:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-mysql    
    volumes:
      - ./data:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome:2.53.0
    links:
     - app
    ports:
      - "4444:4444"
    
