version: '2'
services:    
  # boot:
  #  image: busybox
  #  command: echo Your app is listening at localhost:3000
  #  depends_on: 
  #    - app

  selenium:
    image: selenium/standalone-chrome:2.53.0
    links:
     - app
    ports:
      - "4444:4444"

  app:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-web
    volumes:
      - .:/opt/app
    working_dir: /opt/app/
    command: bash -c "npm install && nodemon"
    links:
      - redis
      - mysql
    ports:
      - "3000:3000"

  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6379"

  mysql:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-mysql    
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/backup
  
    
