FROM node:latest
MAINTAINER Carlos de la Orden <cdelaorden@gmail.com>

# Install nodemon
RUN npm i -g nodemon

# Use changes to package.json to force Docker to NOT use cache
COPY package.json /tmp/package.json
RUN cd /tmp && npm install

# Move installed packages to the app folder
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/

WORKDIR /opt/app
EXPOSE 3000